from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ClearanceCouponSpec:
    values_mm: tuple[float, ...] = (0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40)
    pin_diameter_mm: float = 8.0
    base_thickness_mm: float = 2.4
    test_height_mm: float = 5.0
    spacing_mm: float = 14.0
    facets: int = 80


@dataclass(frozen=True)
class EmbossCouponSpec:
    relief_values_mm: tuple[float, ...] = (0.30, 0.40, 0.50, 0.60, 0.70, 0.80)
    xy_clearance_values_mm: tuple[float, ...] = (0.10, 0.15, 0.20, 0.25, 0.30)
    base_thickness_mm: float = 2.4
    cell_size_mm: float = 14.0
    mark_width_mm: float = 6.0
    mark_line_mm: float = 1.0
    female_extra_depth_mm: float = 0.20
    facets: int = 64


def render_slide_clearance_scad(spec: ClearanceCouponSpec = ClearanceCouponSpec()) -> str:
    """Return OpenSCAD source for a compact plug/pocket clearance coupon.

    Each column contains one removable circular plug and a matching pocket. The
    labels are embossed into the base so values remain identifiable after print.
    """
    values = list(spec.values_mm)
    if not values:
        raise ValueError("At least one clearance value is required")
    if any(v < 0 for v in values):
        raise ValueError("Clearance values cannot be negative")

    width = spec.spacing_mm * len(values) + 8
    depth = 30.0
    lines = [
        "// Generated by EmbossForge calibration generator.",
        f"$fn = {spec.facets};",
        f"base_h = {spec.base_thickness_mm:.4f};",
        f"pin_d = {spec.pin_diameter_mm:.4f};",
        f"test_h = {spec.test_height_mm:.4f};",
        f"spacing = {spec.spacing_mm:.4f};",
        f"plate_w = {width:.4f};",
        f"plate_d = {depth:.4f};",
        "",
        "difference() {",
        "  translate([-plate_w/2, -plate_d/2, 0]) cube([plate_w, plate_d, base_h]);",
    ]
    start = -(len(values) - 1) * spec.spacing_mm / 2
    for i, v in enumerate(values):
        x = start + i * spec.spacing_mm
        lines += [
            f"  translate([{x:.4f}, 6, base_h-0.01]) cylinder(d=pin_d + {2*v:.4f}, h=test_h+0.2);",
        ]
    lines += ["}", ""]
    for i, v in enumerate(values):
        x = start + i * spec.spacing_mm
        lines += [
            f"translate([{x:.4f}, -7, base_h]) cylinder(d=pin_d, h=test_h);",
            f"translate([{x:.4f}, 12, 0.35]) linear_extrude(height=0.35) text(\"{v:.2f}\", size=2.8, halign=\"center\", valign=\"center\");",
        ]
    return "\n".join(lines) + "\n"


def render_emboss_matrix_scad(spec: EmbossCouponSpec = EmbossCouponSpec(), *, female: bool) -> str:
    """Return an emboss test matrix.

    Rows vary relief height and columns vary XY clearance. The male panel uses a
    simple cross mark; the female panel cuts expanded matching cavities. Print
    the two panels and test them with the intended paper stock before choosing
    die defaults.
    """
    reliefs = list(spec.relief_values_mm)
    clearances = list(spec.xy_clearance_values_mm)
    if not reliefs or not clearances:
        raise ValueError("Relief and clearance lists cannot be empty")
    cols, rows = len(clearances), len(reliefs)
    w = cols * spec.cell_size_mm + 8
    d = rows * spec.cell_size_mm + 8
    start_x = -(cols - 1) * spec.cell_size_mm / 2
    start_y = -(rows - 1) * spec.cell_size_mm / 2

    lines = [
        "// Generated by EmbossForge emboss calibration generator.",
        f"$fn = {spec.facets};",
        f"base_h = {spec.base_thickness_mm:.4f};",
        f"cell = {spec.cell_size_mm:.4f};",
        f"mark_w = {spec.mark_width_mm:.4f};",
        f"line_w = {spec.mark_line_mm:.4f};",
        "module mark2d(delta=0) {",
        "  offset(delta=delta) union() {",
        "    square([mark_w, line_w], center=true);",
        "    square([line_w, mark_w], center=true);",
        "  }",
        "}",
        "",
    ]

    if female:
        lines += [
            "difference() {",
            f"  translate([{-w/2:.4f}, {-d/2:.4f}, 0]) cube([{w:.4f}, {d:.4f}, base_h]);",
        ]
        for r, relief in enumerate(reliefs):
            y = start_y + r * spec.cell_size_mm
            for c, clearance in enumerate(clearances):
                x = start_x + c * spec.cell_size_mm
                cavity = relief + spec.female_extra_depth_mm
                lines += [
                    f"  translate([{x:.4f}, {y:.4f}, base_h-{cavity:.4f}]) linear_extrude(height={cavity+0.15:.4f}) mark2d(delta={clearance:.4f});",
                ]
        lines += ["}"]
    else:
        lines += [f"translate([{-w/2:.4f}, {-d/2:.4f}, 0]) cube([{w:.4f}, {d:.4f}, base_h]);"]
        for r, relief in enumerate(reliefs):
            y = start_y + r * spec.cell_size_mm
            for c, _clearance in enumerate(clearances):
                x = start_x + c * spec.cell_size_mm
                lines += [
                    f"translate([{x:.4f}, {y:.4f}, base_h]) linear_extrude(height={relief:.4f}) mark2d();",
                ]

    return "\n".join(lines) + "\n"


def write_calibration_pack(out_dir: str | Path) -> dict[str, str]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    files = {
        "slide_clearance": out / "slide_clearance_coupon.scad",
        "emboss_male": out / "emboss_matrix_male.scad",
        "emboss_female": out / "emboss_matrix_female.scad",
    }
    files["slide_clearance"].write_text(render_slide_clearance_scad(), encoding="utf-8")
    files["emboss_male"].write_text(render_emboss_matrix_scad(female=False), encoding="utf-8")
    files["emboss_female"].write_text(render_emboss_matrix_scad(female=True), encoding="utf-8")
    return {name: str(path) for name, path in files.items()}
