from __future__ import annotations

from dataclasses import asdict
import json
import math
from pathlib import Path

from .config import DieSpec
from .scad_backend import render_scad


# A human-readable preview/reference only. The printable geometry below is built
# directly in OpenSCAD so the micro test does not depend on SVG importer quirks.
BUTTERFLY_SVG = """<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\">\n  <g fill=\"black\">\n    <ellipse cx=\"31\" cy=\"34\" rx=\"20\" ry=\"23\"/>\n    <ellipse cx=\"69\" cy=\"34\" rx=\"20\" ry=\"23\"/>\n    <ellipse cx=\"32\" cy=\"70\" rx=\"16\" ry=\"14\"/>\n    <ellipse cx=\"68\" cy=\"70\" rx=\"16\" ry=\"14\"/>\n    <rect x=\"45\" y=\"27\" width=\"10\" height=\"48\" rx=\"5\"/>\n    <circle cx=\"50\" cy=\"22\" r=\"6\"/>\n  </g>\n</svg>\n"""


def micro_butterfly_spec(*, paper_thickness_mm: float = 0.10) -> DieSpec:
    """Tiny but printable matched die intended for a first embossing test."""
    spec = DieSpec(
        diameter_mm=16.0,
        base_thickness_mm=1.8,
        relief_height_mm=0.45,
        female_xy_clearance_mm=0.20,
        female_extra_depth_mm=0.10,
        paper_thickness_mm=paper_thickness_mm,
        margin_mm=1.5,
        facets=96,
        key_width_mm=3.5,
        key_depth_mm=1.5,
    )
    spec.validate()
    return spec


def _butterfly_2d_scad() -> str:
    """Recognizable, chunky butterfly sized for the 16 mm micro die.

    Four overlapping elliptical wings plus a capsule-like body/head are used
    instead of imported SVG paths. This intentionally favors printability and
    visual recognizability with a 0.4 mm nozzle.
    """
    return """module butterfly2d() {
  union() {
    // upper wings
    translate([-2.7,  1.55]) scale([1.35, 1.00]) circle(r=2.20, $fn=48);
    translate([ 2.7,  1.55]) scale([1.35, 1.00]) circle(r=2.20, $fn=48);
    // lower wings
    translate([-2.6, -2.15]) scale([1.10, 0.85]) circle(r=1.80, $fn=48);
    translate([ 2.6, -2.15]) scale([1.10, 0.85]) circle(r=1.80, $fn=48);
    // body and head
    hull() {
      translate([0, -2.7]) circle(r=0.68, $fn=32);
      translate([0,  2.5]) circle(r=0.68, $fn=32);
    }
    translate([0, 3.35]) circle(r=0.82, $fn=32);
  }
}
"""


def _carrier_base_2d_scad(spec: DieSpec) -> str:
    overlap = 0.5
    tab_depth = spec.key_depth_mm + overlap
    tab_y = spec.diameter_mm / 2 + (spec.key_depth_mm - overlap) / 2
    return f"""module carrier2d() {{
  union() {{
    circle(d={spec.diameter_mm:.4f}, $fn={spec.facets});
    translate([0, {tab_y:.4f}]) square([{spec.key_width_mm:.4f}, {tab_depth:.4f}], center=true);
  }}
}}
"""


def _male_scad(spec: DieSpec) -> str:
    return f"""// Generated by EmbossForge: direct-geometry micro butterfly male die.
$fn = {spec.facets};
{_carrier_base_2d_scad(spec)}
{_butterfly_2d_scad()}
union() {{
  linear_extrude(height={spec.base_thickness_mm:.4f}) carrier2d();
  translate([0, 0, {spec.base_thickness_mm:.4f}])
    linear_extrude(height={spec.relief_height_mm:.4f}) butterfly2d();
}}
"""


def _female_scad(spec: DieSpec) -> str:
    cavity = spec.female_cavity_depth_mm
    return f"""// Generated by EmbossForge: direct-geometry micro butterfly female die.
$fn = {spec.facets};
{_carrier_base_2d_scad(spec)}
{_butterfly_2d_scad()}
difference() {{
  linear_extrude(height={spec.base_thickness_mm:.4f}) carrier2d();
  translate([0, 0, {spec.base_thickness_mm - cavity:.4f}])
    linear_extrude(height={cavity + 0.15:.4f})
      offset(delta={spec.female_xy_clearance_mm:.4f}) butterfly2d();
}}
"""


def _solid_pair_mass_upper_bound_g(spec: DieSpec, *, pla_density_g_cm3: float = 1.24) -> float:
    overlap_mm = 0.5
    carrier_area_mm2 = (
        math.pi * (spec.diameter_mm / 2) ** 2
        + spec.key_width_mm * (spec.key_depth_mm + overlap_mm)
    )
    pair_base_volume_mm3 = 2 * carrier_area_mm2 * spec.base_thickness_mm
    male_relief_bound_mm3 = math.pi * spec.artwork_radius_mm**2 * spec.relief_height_mm
    return ((pair_base_volume_mm3 + male_relief_bound_mm3) / 1000.0) * pla_density_g_cm3


def export_micro_butterfly_test(
    out_dir: str | Path,
    *,
    paper_thickness_mm: float = 0.10,
) -> dict[str, str]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    spec = micro_butterfly_spec(paper_thickness_mm=paper_thickness_mm)
    artwork = out / "micro_butterfly.svg"
    artwork.write_text(BUTTERFLY_SVG, encoding="utf-8")

    male_scad = out / "micro_butterfly_male.scad"
    female_scad = out / "micro_butterfly_female.scad"
    male_stl = out / "micro_butterfly_male.stl"
    female_stl = out / "micro_butterfly_female.stl"

    male_scad.write_text(_male_scad(spec), encoding="utf-8")
    female_scad.write_text(_female_scad(spec), encoding="utf-8")
    render_scad(male_scad, male_stl)
    render_scad(female_scad, female_stl)

    outputs = {
        "male_scad": male_scad,
        "female_scad": female_scad,
        "male_stl": male_stl,
        "female_stl": female_stl,
    }

    # Dedicated manifest for this direct-geometry test. Keeping it separate
    # avoids implying that the SVG importer produced these STL reliefs.
    pair_manifest = out / "micro_butterfly_manifest.json"
    pair_manifest.write_text(
        json.dumps(
            {
                "name": "micro_butterfly",
                "geometry_source": "direct OpenSCAD primitives (SVG is preview/reference only)",
                "spec": asdict(spec),
                "derived": {
                    "artwork_radius_mm": spec.artwork_radius_mm,
                    "female_cavity_depth_mm": spec.female_cavity_depth_mm,
                    "carrier_depth_mm": spec.carrier_depth_mm,
                },
                "outputs": {key: str(value) for key, value in outputs.items()},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    outputs["manifest"] = pair_manifest

    mass_bound = _solid_pair_mass_upper_bound_g(spec)
    manifest = out / "micro_butterfly_test_manifest.json"
    manifest.write_text(
        json.dumps(
            {
                "purpose": "Ultra-low-filament first real male/female embossing test",
                "design": "chunky direct-geometry butterfly silhouette",
                "spec": asdict(spec),
                "solid_pair_mass_upper_bound_g": round(mass_bound, 3),
                "printing_note": (
                    "Slice the male and female STL together at 100% scale. "
                    "Trust FlashPrint's material estimate before printing and leave extra filament for printer purge/prime."
                ),
                "use_note": (
                    "This pair is meant for light test embossing only. Align the tabs, place paper between the faces, "
                    "and press gently between two flat hard surfaces or with a small clamp/pliers with flat jaws."
                ),
                "outputs": {key: str(value) for key, value in outputs.items()},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    result = {key: str(value) for key, value in outputs.items()}
    result["artwork"] = str(artwork)
    result["test_manifest"] = str(manifest)
    result["solid_pair_mass_upper_bound_g"] = f"{mass_bound:.2f}"
    return result
