from __future__ import annotations

from dataclasses import asdict
import json
import math
from pathlib import Path

from .config import DieSpec
from .scad_backend import render_scad


# A human-readable preview/reference only. The printable geometry below is built
# directly in OpenSCAD so the micro test does not depend on SVG importer quirks.
BUTTERFLY_SVG = """<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\">\n  <g fill=\"black\">\n    <ellipse cx=\"31\" cy=\"34\" rx=\"20\" ry=\"23\"/>\n    <ellipse cx=\"69\" cy=\"34\" rx=\"20\" ry=\"23\"/>\n    <ellipse cx=\"32\" cy=\"70\" rx=\"16\" ry=\"14\"/>\n    <ellipse cx=\"68\" cy=\"70\" rx=\"16\" ry=\"14\"/>\n    <rect x=\"45\" y=\"27\" width=\"10\" height=\"48\" rx=\"5\"/>\n    <circle cx=\"50\" cy=\"22\" r=\"6\"/>\n  </g>\n</svg>\n"""


def micro_butterfly_spec(*, paper_thickness_mm: float = 0.10) -> DieSpec:
    """Tiny matched die preserving the exact physically successful cavity geometry.

    The first printed article used a 0.65 mm female cavity (0.45 mm male relief +
    the historical 0.10 mm paper allowance + 0.10 mm extra allowance). The general
    cavity semantics were later corrected so paper thickness is handled by closure,
    not cavity depth. To keep this reference artifact reproducible, its explicit
    extra-depth value is now 0.20 mm, yielding the same 0.65 mm physical cavity.
    New general-purpose dies should use the corrected tighter engagement defaults.
    """
    spec = DieSpec(
        diameter_mm=16.0,
        base_thickness_mm=1.8,
        relief_height_mm=0.45,
        female_xy_clearance_mm=0.20,
        female_extra_depth_mm=0.20,
        paper_thickness_mm=paper_thickness_mm,
        margin_mm=1.5,
        facets=96,
        key_width_mm=3.5,
        key_depth_mm=1.5,
    )
    spec.validate()
    return spec


def _butterfly_2d_scad() -> str:
    """Recognizable, chunky butterfly sized for the 16 mm micro die."""
    return """module butterfly2d() {
  union() {
    translate([-2.7,  1.55]) scale([1.35, 1.00]) circle(r=2.20, $fn=48);
    translate([ 2.7,  1.55]) scale([1.35, 1.00]) circle(r=2.20, $fn=48);
    translate([-2.6, -2.15]) scale([1.10, 0.85]) circle(r=1.80, $fn=48);
    translate([ 2.6, -2.15]) scale([1.10, 0.85]) circle(r=1.80, $fn=48);
    hull() {
      translate([0, -2.7]) circle(r=0.68, $fn=32);
      translate([0,  2.5]) circle(r=0.68, $fn=32);
    }
    translate([0, 3.35]) circle(r=0.82, $fn=32);
  }
}
"""


def _carrier_base_2d_scad(spec: DieSpec) -> str:
    overlap = 0.5
    tab_depth = spec.key_depth_mm + overlap
    tab_y = spec.diameter_mm / 2 + (spec.key_depth_mm - overlap) / 2
    return f"""module carrier2d() {{
  union() {{
    circle(d={spec.diameter_mm:.4f}, $fn={spec.facets});
    translate([0, {tab_y:.4f}]) square([{spec.key_width_mm:.4f}, {tab_depth:.4f}], center=true);
  }}
}}
"""


def _male_scad(spec: DieSpec) -> str:
    return f"""// Generated by EmbossForge: direct-geometry micro butterfly male die.
$fn = {spec.facets};
{_carrier_base_2d_scad(spec)}
{_butterfly_2d_scad()}
union() {{
  linear_extrude(height={spec.base_thickness_mm:.4f}) carrier2d();
  translate([0, 0, {spec.base_thickness_mm:.4f}])
    linear_extrude(height={spec.relief_height_mm:.4f}) butterfly2d();
}}
"""


def _female_scad(spec: DieSpec) -> str:
    cavity = spec.female_cavity_depth_mm
    return f"""// Generated by EmbossForge: direct-geometry micro butterfly female die.
$fn = {spec.facets};
{_carrier_base_2d_scad(spec)}
{_butterfly_2d_scad()}
difference() {{
  linear_extrude(height={spec.base_thickness_mm:.4f}) carrier2d();
  translate([0, 0, {spec.base_thickness_mm - cavity:.4f}])
    linear_extrude(height={cavity + 0.15:.4f})
      offset(delta={spec.female_xy_clearance_mm:.4f}) butterfly2d();
}}
"""


def _solid_pair_mass_upper_bound_g(spec: DieSpec) -> float:
    """Conservative historical helper retained for test/API compatibility."""
    radius_cm = (spec.diameter_mm / 2) / 10
    base_cm = spec.base_thickness_mm / 10
    relief_cm = spec.relief_height_mm / 10
    carrier = math.pi * radius_cm * radius_cm * base_cm
    tab_cm3 = (spec.key_width_mm / 10) * (spec.key_depth_mm / 10) * base_cm
    artwork_fraction = 0.42
    male_relief = math.pi * (spec.artwork_radius_mm / 10) ** 2 * relief_cm * artwork_fraction
    pair_cm3 = 2 * (carrier + tab_cm3) + male_relief
    return pair_cm3 * 1.24


def export_micro_butterfly_test(
    out_dir: str | Path,
    *,
    paper_thickness_mm: float = 0.10,
) -> dict[str, str | float]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    spec = micro_butterfly_spec(paper_thickness_mm=paper_thickness_mm)

    artwork = out / "micro_butterfly.svg"
    artwork.write_text(BUTTERFLY_SVG, encoding="utf-8")
    male_scad = out / "micro_butterfly_male.scad"
    female_scad = out / "micro_butterfly_female.scad"
    male_scad.write_text(_male_scad(spec), encoding="utf-8")
    female_scad.write_text(_female_scad(spec), encoding="utf-8")

    male_stl = render_scad(male_scad, out / "micro_butterfly_male.stl")
    female_stl = render_scad(female_scad, out / "micro_butterfly_female.stl")
    mass = _solid_pair_mass_upper_bound_g(spec)

    manifest = out / "micro_butterfly_manifest.json"
    data = {
        "purpose": "ultra-low-filament real matched emboss test",
        "physical_reference_geometry_preserved": True,
        "spec": asdict(spec),
        "derived": {
            "female_cavity_depth_mm": spec.female_cavity_depth_mm,
            "solid_pair_mass_upper_bound_g": round(mass, 3),
        },
        "instructions": [
            "Print male and female at 100% scale with artwork faces upward.",
            "Align the +Y orientation tabs when testing by hand.",
            "Place scrap paper between the faces and squeeze gently between flat plates or a small clamp.",
            "This artifact intentionally preserves the cavity geometry of the first physically successful print.",
        ],
    }
    manifest.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")

    return {
        "artwork": str(artwork),
        "male_scad": str(male_scad),
        "female_scad": str(female_scad),
        "male_stl": str(male_stl),
        "female_stl": str(female_stl),
        "test_manifest": str(manifest),
        "solid_pair_mass_upper_bound_g": round(mass, 3),
    }
