from __future__ import annotations

from dataclasses import asdict
import json
from pathlib import Path

from .config import DieSpec
from .heightmap import HeightMapResult
from .relief import ReliefSpec
from .scad_backend import render_scad


def generate_relief_die_pair(
    heightmap: HeightMapResult,
    female_surface_map: Path,
    max_cavity_mm: float,
    output_dir: str | Path,
    name: str,
    spec: DieSpec,
    relief_spec: ReliefSpec,
    *,
    render_stl: bool = True,
) -> dict[str, Path]:
    """Generate matched variable-depth dies from canonical surface maps."""
    spec.validate()
    relief_spec.validate()
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    male_scad = out / f"{name}_male.scad"
    female_scad = out / f"{name}_female.scad"
    male_stl = out / f"{name}_male.stl"
    female_stl = out / f"{name}_female.stl"
    manifest = out / f"{name}_manifest.json"

    male_scad.write_text(_male_scad(heightmap, spec, relief_spec), encoding="utf-8")
    female_scad.write_text(
        _female_scad(heightmap, female_surface_map, max_cavity_mm, spec),
        encoding="utf-8",
    )

    outputs: dict[str, Path] = {
        "male_scad": male_scad,
        "female_scad": female_scad,
        "heightmap": heightmap.machine_heightmap,
        "male_surface_map": heightmap.male_surface_map,
        "female_surface_map": female_surface_map,
        "manifest": manifest,
    }

    if render_stl:
        render_scad(male_scad, male_stl)
        render_scad(female_scad, female_stl)
        outputs["male_stl"] = male_stl
        outputs["female_stl"] = female_stl

    manifest.write_text(
        json.dumps(
            {
                "schema_version": 2,
                "name": name,
                "artwork": str(heightmap.machine_heightmap.resolve()),
                "spec": asdict(spec),
                "derived": {
                    "artwork_radius_mm": spec.artwork_radius_mm,
                    "female_cavity_depth_mm": max_cavity_mm,
                    "carrier_depth_mm": spec.carrier_depth_mm,
                },
                "orientation": {
                    "carrier_key": "+Y on both printed inserts",
                    "upper_install_transform": "rotate 180 degrees about Y with the upper cartridge",
                    "female_artwork_compensation": "height field mirrored in X before cavity generation",
                },
                "relief": {
                    "mode": "relief",
                    **relief_spec.to_dict(),
                    "sampling": {
                        "width_px": heightmap.width_px,
                        "height_px": heightmap.height_px,
                        "mm_per_sample": heightmap.mm_per_sample,
                    },
                    "filtered_pixels": heightmap.filtered_pixels,
                },
                "outputs": {key: str(value) for key, value in outputs.items() if key != "manifest"},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return outputs


def _carrier_base_scad(spec: DieSpec) -> str:
    overlap = 0.5
    tab_depth = spec.key_depth_mm + overlap
    tab_y = spec.diameter_mm / 2 + (spec.key_depth_mm - overlap) / 2
    return (
        "union() { "
        "circle(d=die_d, $fn=$fn); "
        f"translate([0, {tab_y:.4f}]) square([{spec.key_width_mm:.4f}, {tab_depth:.4f}], center=true); "
        "}"
    )


def _surface_module(image: Path, heightmap: HeightMapResult, spec: DieSpec, z_height: float) -> str:
    escaped = str(image.resolve()).replace("\\", "/").replace('"', '\\"')
    sx = spec.artwork_box_mm / max(1, heightmap.width_px - 1)
    sy = spec.artwork_box_mm / max(1, heightmap.height_px - 1)
    sz = z_height / 255.0
    return (
        f'translate([-art_box/2, -art_box/2, 0]) '
        f'scale([{sx:.8f}, {sy:.8f}, {sz:.8f}]) '
        f'surface(file="{escaped}", center=false, invert=false, convexity=10);'
    )


def _male_scad(heightmap: HeightMapResult, spec: DieSpec, relief_spec: ReliefSpec) -> str:
    base_expr = _carrier_base_scad(spec)
    surface = _surface_module(heightmap.male_surface_map, heightmap, spec, relief_spec.max_relief_mm)
    return f"""// Generated by EmbossForge variable-depth backend. Do not edit by hand.
$fn = {spec.facets};
die_d = {spec.diameter_mm:.4f};
base_h = {spec.base_thickness_mm:.4f};
art_box = {spec.artwork_box_mm:.4f};
art_r = {spec.artwork_radius_mm:.4f};
relief_h = {relief_spec.max_relief_mm:.4f};

module relief_solid() {{
  {surface}
}}

union() {{
  linear_extrude(height=base_h)
    {base_expr}
  translate([0, 0, base_h])
    intersection() {{
      cylinder(r=art_r, h=relief_h + 0.02, $fn=$fn);
      relief_solid();
    }}
}}
"""


def _female_scad(
    heightmap: HeightMapResult,
    female_surface_map: Path,
    max_cavity_mm: float,
    spec: DieSpec,
) -> str:
    base_expr = _carrier_base_scad(spec)
    surface = _surface_module(female_surface_map, heightmap, spec, max_cavity_mm)
    return f"""// Generated by EmbossForge variable-depth backend. Do not edit by hand.
$fn = {spec.facets};
die_d = {spec.diameter_mm:.4f};
base_h = {spec.base_thickness_mm:.4f};
art_box = {spec.artwork_box_mm:.4f};
art_r = {spec.artwork_radius_mm + spec.female_xy_clearance_mm:.4f};
cavity_h = {max_cavity_mm:.4f};

module cavity_solid() {{
  {surface}
}}

difference() {{
  linear_extrude(height=base_h)
    {base_expr}
  translate([0, 0, base_h])
    mirror([0, 0, 1])
      intersection() {{
        cylinder(r=art_r, h=cavity_h + 0.02, $fn=$fn);
        cavity_solid();
      }}
}}
"""
