from __future__ import annotations

from dataclasses import asdict
import json
from pathlib import Path
import shutil
import subprocess

from .config import DieSpec


def find_openscad() -> Path | None:
    candidates = []
    found = shutil.which("openscad") or shutil.which("OpenSCAD")
    if found:
        candidates.append(Path(found))
    candidates.extend(
        [
            Path(r"C:\Program Files\OpenSCAD\openscad.exe"),
            Path(r"C:\Program Files (x86)\OpenSCAD\openscad.exe"),
            Path("/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD"),
            Path("/usr/bin/openscad"),
            Path("/usr/local/bin/openscad"),
        ]
    )
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def generate_die_pair(
    artwork_svg: str | Path,
    output_dir: str | Path,
    name: str,
    spec: DieSpec,
    *,
    render_stl: bool = True,
) -> dict[str, Path]:
    spec.validate()
    art = Path(artwork_svg).resolve()
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    male_scad = out / f"{name}_male.scad"
    female_scad = out / f"{name}_female.scad"
    male_stl = out / f"{name}_male.stl"
    female_stl = out / f"{name}_female.stl"
    manifest = out / f"{name}_manifest.json"

    male_scad.write_text(_male_scad(art, spec), encoding="utf-8")
    female_scad.write_text(_female_scad(art, spec), encoding="utf-8")

    outputs: dict[str, Path] = {
        "male_scad": male_scad,
        "female_scad": female_scad,
        "manifest": manifest,
    }

    openscad = find_openscad()
    if render_stl:
        if openscad is None:
            raise RuntimeError(
                "OpenSCAD executable was not found. Add it to PATH or install it in the default location. "
                "The .scad files were still generated."
            )
        _render(openscad, male_scad, male_stl)
        _render(openscad, female_scad, female_stl)
        outputs["male_stl"] = male_stl
        outputs["female_stl"] = female_stl

    manifest.write_text(
        json.dumps(
            {
                "name": name,
                "artwork": str(art),
                "spec": asdict(spec),
                "outputs": {key: str(value) for key, value in outputs.items() if key != "manifest"},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return outputs


def _art_module(art: Path, spec: DieSpec, *, delta: float = 0.0, mirror_y: bool = False) -> str:
    escaped = str(art).replace("\\", "/").replace('"', '\\"')
    mirror = "mirror([0, 1, 0]) " if mirror_y else ""
    return (
        f"{mirror}offset(delta={delta:.4f}) "
        f"resize([{spec.artwork_box_mm:.4f}, {spec.artwork_box_mm:.4f}], auto=true) "
        f'import(file="{escaped}", center=true);'
    )


def _male_scad(art: Path, spec: DieSpec) -> str:
    art_expr = _art_module(art, spec)
    return f"""// Generated by EmbossForge. Do not edit by hand.\n$fn = {spec.facets};\n\ndie_d = {spec.diameter_mm:.4f};\nbase_h = {spec.base_thickness_mm:.4f};\nrelief_h = {spec.relief_height_mm:.4f};\n\nunion() {{\n  cylinder(d=die_d, h=base_h);\n  translate([0, 0, base_h])\n    linear_extrude(height=relief_h)\n      {art_expr}\n}}\n"""


def _female_scad(art: Path, spec: DieSpec) -> str:
    art_expr = _art_module(art, spec, delta=spec.female_xy_clearance_mm, mirror_y=True)
    cavity = spec.female_cavity_depth_mm
    return f"""// Generated by EmbossForge. Do not edit by hand.\n// The cavity artwork is mirrored in Y so an upper die flipped to face the male aligns correctly.\n$fn = {spec.facets};\n\ndie_d = {spec.diameter_mm:.4f};\nbase_h = {spec.base_thickness_mm:.4f};\ncavity_h = {cavity:.4f};\n\ndifference() {{\n  cylinder(d=die_d, h=base_h);\n  translate([0, 0, base_h - cavity_h])\n    linear_extrude(height=cavity_h + 0.15)\n      {art_expr}\n}}\n"""


def _render(openscad: Path, source_scad: Path, output_stl: Path) -> None:
    result = subprocess.run(
        [str(openscad), "-o", str(output_stl), str(source_scad)],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        message = result.stderr.strip() or result.stdout.strip() or "OpenSCAD failed without diagnostic output"
        raise RuntimeError(f"OpenSCAD failed rendering {source_scad.name}: {message}")
