"""Load a generated EmbossForge mechanical assembly into Blender.

Run from the repository root after `embossforge mechanics`:

    blender --python blender/import_assembly.py -- build/mechanics open

or, inside Blender's Scripting workspace, set BUILD_DIR / STATE below and run.
The script intentionally contains no project design logic: dimensions and
placements remain generated by the Python/CadQuery source of truth.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
import sys

import bpy
from mathutils import Euler, Matrix


DEFAULT_BUILD_DIR = Path("build/mechanics")
DEFAULT_STATE = "open"


def _argv() -> tuple[Path, str]:
    if "--" not in sys.argv:
        return DEFAULT_BUILD_DIR, DEFAULT_STATE
    args = sys.argv[sys.argv.index("--") + 1 :]
    build_dir = Path(args[0]) if args else DEFAULT_BUILD_DIR
    state = args[1] if len(args) > 1 else DEFAULT_STATE
    if state not in {"open", "closed"}:
        raise SystemExit("state must be 'open' or 'closed'")
    return build_dir, state


def _clear_scene() -> None:
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for collection in list(bpy.data.collections):
        if collection.name != "Collection" and collection.users == 0:
            bpy.data.collections.remove(collection)


def _import_stl(path: Path):
    before = set(bpy.context.scene.objects)
    # Blender 4.x exposes the built-in STL importer as wm.stl_import. Older
    # installations may still use import_mesh.stl.
    if hasattr(bpy.ops.wm, "stl_import"):
        bpy.ops.wm.stl_import(filepath=str(path.resolve()))
    elif hasattr(bpy.ops.import_mesh, "stl"):
        bpy.ops.import_mesh.stl(filepath=str(path.resolve()))
    else:
        raise RuntimeError("No STL importer is available in this Blender installation")
    created = [obj for obj in bpy.context.scene.objects if obj not in before]
    if len(created) != 1:
        raise RuntimeError(f"Expected one object from {path}, got {len(created)}")
    return created[0]


def _matrix(entry: dict) -> Matrix:
    pre = entry.get("pre_translation_mm", [0.0, 0.0, 0.0])
    rotation = entry.get("rotation_deg_xyz", [0.0, 0.0, 0.0])
    translation = entry.get("translation_mm", [0.0, 0.0, 0.0])
    pre_m = Matrix.Translation(pre)
    rot_m = Euler(tuple(math.radians(v) for v in rotation), "XYZ").to_matrix().to_4x4()
    world_m = Matrix.Translation(translation)
    return world_m @ rot_m @ pre_m


def _material(name: str, rgba: tuple[float, float, float, float]):
    mat = bpy.data.materials.get(name) or bpy.data.materials.new(name)
    mat.diffuse_color = rgba
    return mat


def _add_hardware(manifest: dict, layout: dict, state: str) -> None:
    press = manifest["press"]
    derived = manifest["derived"]
    hardware_mat = _material("Hardware", (0.18, 0.20, 0.22, 1.0))

    # Two vertical guide rods. Their generated length includes the sockets in
    # the base and top bridge.
    rod_radius = press["guide_rod_diameter_mm"] / 2
    rod_length = derived["guide_rod_length"]
    rod_bottom = press["base_thickness_mm"] - press["guide_rod_socket_depth_mm"]
    rod_z = rod_bottom + rod_length / 2
    rod_y = derived["lower_y"]
    rod_x = press["guide_rod_spacing_mm"] / 2
    for sign, label in ((-1, "guide_rod_left"), (1, "guide_rod_right")):
        bpy.ops.mesh.primitive_cylinder_add(
            vertices=48,
            radius=rod_radius,
            depth=rod_length,
            location=(sign * rod_x, rod_y, rod_z),
        )
        obj = bpy.context.object
        obj.name = label
        obj.data.materials.append(hardware_mat)

    # Main lever pivot, axis X.
    pivot_len = press["top_bridge_width_mm"]
    bpy.ops.mesh.primitive_cylinder_add(
        vertices=48,
        radius=press["pivot_diameter_mm"] / 2,
        depth=pivot_len,
        location=(0, derived["pivot_y"], derived["pivot_world_z"]),
        rotation=(0, math.radians(90), 0),
    )
    pivot = bpy.context.object
    pivot.name = "main_pivot_preview"
    pivot.data.materials.append(hardware_mat)


def main() -> None:
    build_dir, state = _argv()
    layout_path = build_dir / "assembly_layout.json"
    manifest_path = build_dir / "mechanics_manifest.json"
    if not layout_path.exists():
        raise SystemExit(f"Missing {layout_path}; run `embossforge mechanics` first")

    layout = json.loads(layout_path.read_text(encoding="utf-8"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else None
    entries = layout["states"][state]

    _clear_scene()
    scene = bpy.context.scene
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.length_unit = "MILLIMETERS"
    scene.unit_settings.scale_length = 0.001

    printed_mat = _material("PrintedParts", (0.34, 0.39, 0.45, 1.0))
    cartridge_mat = _material("Cartridges", (0.52, 0.42, 0.28, 1.0))

    for instance_name, entry in entries.items():
        source = entry.get("source", instance_name)
        path = build_dir / f"{source}.stl"
        if not path.exists():
            raise RuntimeError(f"Missing generated STL for {instance_name}: {path}")
        obj = _import_stl(path)
        obj.name = instance_name
        obj.matrix_world = _matrix(entry)
        obj.data.materials.append(cartridge_mat if "cartridge" in instance_name else printed_mat)

    if manifest:
        _add_hardware(manifest, layout, state)

    # Select everything and frame it. This leaves the scene ready for Astra or
    # a human to inspect without asking an agent to recreate the assembly.
    bpy.ops.object.select_all(action="SELECT")
    if bpy.context.screen:
        for area in bpy.context.screen.areas:
            if area.type == "VIEW_3D":
                override = {"area": area, "region": next((r for r in area.regions if r.type == "WINDOW"), None)}
                if override["region"]:
                    with bpy.context.temp_override(**override):
                        bpy.ops.view3d.view_selected(use_all_regions=False)
                break

    print(f"EmbossForge: loaded {state} assembly from {build_dir}")


if __name__ == "__main__":
    main()
