"""Parametric mechanical components for EmbossForge."""

from .cad import (
    build_assembly_preview,
    build_cartridge,
    build_press_parts,
    build_receiver,
    export_press_pack,
    mechanical_layout,
    validate_assembly_clearance,
)
from .handheld_compact import (
    HandLeverSpec,
    build_hand_lever,
    build_hand_lever_assembly,
    build_hand_lever_body,
    build_upper_backing_cap,
    build_upper_carriage,
    export_hand_lever_press_pack as export_blocky_hand_lever_press_pack,
    hand_lever_spec,
    standard_handheld_die_spec,
    validate_hand_lever_clearance,
)
from .handheld_elegant import (
    build_elegant_assembly,
    build_elegant_body,
    build_elegant_lever,
    build_elegant_upper_cap,
    build_elegant_upper_carriage,
    elegant_lever_spec,
    export_elegant_lever_press_pack,
    validate_elegant_clearance,
)
from .handheld_lean_test import (
    build_lean_test_assembly,
    build_lean_test_body,
    build_lean_test_lever,
    build_lean_test_upper_cap,
    build_lean_test_upper_carriage,
    build_printed_cap_peg,
    build_printed_drive_pin,
    build_printed_drive_retainer,
    build_printed_main_pivot,
    build_printed_main_pivot_retainer,
    export_lean_test_press_pack,
    lean_test_spec,
    validate_lean_test_clearance,
)
from .micro import (
    MicroTongsSpec,
    build_micro_tongs,
    build_micro_tongs_print_orientation,
    export_micro_press_pack,
    micro_tongs_spec,
)
from .mini import export_mini_test_pack, mini_cartridge_spec, mini_die_spec, mini_press_spec
from .spec import CartridgeSpec, PressSpec

# Public default: the sculpted V3. The old V2 export remains available explicitly.
export_hand_lever_press_pack = export_elegant_lever_press_pack

__all__ = [
    "CartridgeSpec",
    "PressSpec",
    "build_cartridge",
    "build_receiver",
    "build_press_parts",
    "build_assembly_preview",
    "mechanical_layout",
    "validate_assembly_clearance",
    "export_press_pack",
    "HandLeverSpec",
    "hand_lever_spec",
    "standard_handheld_die_spec",
    "build_hand_lever_body",
    "build_upper_carriage",
    "build_upper_backing_cap",
    "build_hand_lever",
    "build_hand_lever_assembly",
    "validate_hand_lever_clearance",
    "export_blocky_hand_lever_press_pack",
    "elegant_lever_spec",
    "build_elegant_body",
    "build_elegant_upper_carriage",
    "build_elegant_upper_cap",
    "build_elegant_lever",
    "build_elegant_assembly",
    "validate_elegant_clearance",
    "export_elegant_lever_press_pack",
    "export_hand_lever_press_pack",
    "lean_test_spec",
    "build_lean_test_body",
    "build_lean_test_upper_carriage",
    "build_lean_test_upper_cap",
    "build_lean_test_lever",
    "build_lean_test_assembly",
    "validate_lean_test_clearance",
    "build_printed_main_pivot",
    "build_printed_main_pivot_retainer",
    "build_printed_drive_pin",
    "build_printed_drive_retainer",
    "build_printed_cap_peg",
    "export_lean_test_press_pack",
    "mini_cartridge_spec",
    "mini_press_spec",
    "mini_die_spec",
    "export_mini_test_pack",
    "MicroTongsSpec",
    "micro_tongs_spec",
    "build_micro_tongs",
    "build_micro_tongs_print_orientation",
    "export_micro_press_pack",
]
